[samples]
1 = {name = "Kick1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/36-Pearl22Kick-1.raw"}
2 = {name = "Kick2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/36-Pearl22Kick-3.raw"}
3 = {name = "Kick3", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/36-Pearl22Kick-5.raw"}
4 = {name = "Snare1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/38-PearlSnare2-1.raw"}
5 = {name = "Snare2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/38-PearlSnare2-3.raw"}
6 = {name = "Snare3", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/38-PearlSnare2-5.raw"}
7 = {name = "SnareEdge1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/40-PearlSnare2Edge-1.raw"}
8 = {name = "SnareEdge2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/40-PearlSnare2Edge-3.raw"}
9 = {name = "Cowbell", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/56-Cowbell-1.raw"}
10 = {name = "Maraca", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/64-Maraca-3.raw"}
11 = {name = "Crash1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/57-SabianAAX17Crash-1.raw"}
12 = {name = "Crash2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/57-SabianAAX17Crash-3.raw"}
13 = {name = "Crash3", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/49-SabianAA16Crash-1.raw"}
14 = {name = "Sidestick1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/37-Sidestick2-1.raw"}
15 = {name = "Sidestick2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/37-Sidestick2-3.raw"}
16 = {name = "FloorTom1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/41-Pearl16FloorTom-1.raw"}
17 = {name = "FloorTom2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/41-Pearl16FloorTom-3.raw"}
18 = {name = "HatClosed1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/42-SabianRockHatClosed-1.raw"}
19 = {name = "HatClosed2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/42-SabianRockHatClosed-2.raw"}
20 = {name = "HatClosed3", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/42-SabianRockHatClosed-3.raw"}
21 = {name = "HatPedal1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/44-SabianRockHatPedal-1.raw"}
22 = {name = "HatPedal2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/44-SabianRockHatPedal-3.raw"}
23 = {name = "HatPedal3", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/44-SabianRockHatPedal-5.raw"}
24 = {name = "Tom1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/45-Pearl12Tom-1.raw"}
25 = {name = "Tom2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/45-Pearl12Tom-2.raw"}
26 = {name = "Tom3", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/45-Pearl12Tom-3.raw"}
27 = {name = "Tom4", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/47-Pearl13Tom2-1.raw"}
28 = {name = "Tom5", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/47-Pearl13Tom2-2.raw"}
29 = {name = "Tom6", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/47-Pearl13Tom2-3.raw"}
30 = {name = "HatSemiOpen1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/46-SabianRockHatSemiOpen-1.raw"}
31 = {name = "HatSemiOpen2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/46-SabianRockHatSemiOpen-3.raw"}
32 = {name = "Ride1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/51-SabianAAX20Ride-1.raw"}
33 = {name = "Ride2", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/51-SabianAAX20Ride-2.raw"}
34 = {name = "BongoHi1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoHi-Soft.raw"}
35 = {name = "BongoHi2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoHi-Med.raw"}
36 = {name = "BongoLo1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoLo-Soft.raw"}
37 = {name = "BongoLo2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoLo-Med.raw"}
38 = {name = "CajonSlaps1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonSlaps-Soft.raw"}
39 = {name = "CajonSlaps2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonSlaps-Med.raw"}
40 = {name = "CajonThumps1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonThumps-Soft.raw"}
41 = {name = "CajonThumps2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonThumps-Med.raw"}
42 = {name = "Clave1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Clave-Soft.raw"}
43 = {name = "Clave2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Clave-Med.raw"}
44 = {name = "FingerSnap1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Fingersnap-Soft.raw"}
45 = {name = "FingerSnap2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Fingersnap-Med.raw"}
46 = {name = "HandClap1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/HandClap-Soft.raw"}
47 = {name = "HandClap2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/HandClap-Med.raw"}
48 = {name = "Maraca1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Maraca-Soft.raw"}
49 = {name = "Maraca2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Maraca-Med.raw"}
50 = {name = "Tambourine", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Tambourine-Med.raw"}
