name = "wnm_ps1_simulator"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm_ps1_simulator"]
[[depends-on]]
asfml = "^2.5.2"
[[depends-on]]
hal = "~0.3.0"
[[depends-on]]
bbqueue = "~0.3.0"
[[depends-on]]
resources = "~0.1.0"
