name = "wnm_rom_builder"
description = "Shiny new project"
version = "0.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm_rom_builder"]

[[depends-on]]
fsmaker = "~0.0.0"
hal = "~0.3.0"

[[pins]]
fsmaker = { url="git@github.com:Fabien-Chouteau/fsmaker.git" }
littlefs = { url = "git@github.com:Fabien-Chouteau/littlefs-ada.git" }

[build-profiles]
fsmaker = "Development"
littlefs = "Development"

[configuration.values]
littlefs.Assert = true
littlefs.Debug = true
littlefs.Warn = true
littlefs.Error = true
littlefs.Trace = true
littlefs.No_Malloc = false
